name: blood-cell-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - altair
  - ipykernel
  - pip
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - pip:
    - tensorflow==2.13.0
    - tensorflow_hub